services:
  http_exporter:
    image: local/mrdan4es/http_exporter
    ports:
      - "322:322"
    volumes:
      - ./config.example.yml:/tmp/config.yml
    command: ["--config", "/tmp/config.yml"]
    env_file:
      - .env.example
