services:
  http_exporter:
    image: ghcr.io/mrdan4es/http_exporter:latest
    ports:
      - "322:322"
    volumes:
      - ./config.example.yml:/tmp/config.yml
    command: ["--config", "/tmp/config.yml"]
    env_file:
      - .env.example
